[package]
name = "codebreaker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
rand = "0.8"
hypercube = { path = "../hypercube" }

[dev-dependencies]
tempfile = "3"
